var offer_data = [
	{
		"offer_type":"餐饮",
		"offer_code":"1002",
		"offer-airlines":[
			{
				"offer-vendor-name":"中国东方航空",
				"offer-vendor-intro":"东航航线覆盖全球179个国家、1057个目的地。是天合联盟成员。",
				"offer-rules_cart":[
					{
						"offer-rule-title":"适用卡别:",
						"offer-rule-con":
					},
					{
						"offer-rule-title":"发行地区:",
						"offer-rule-con":"中国大陆"
					},
					{
						"offer-rule-title":"兑现城市:",
						"offer-rule-con":"中国多个城市"
					}
				],
				"offer-privileges":[
					{
						"offer-privilege_name":"尊享礼遇",
						"offer-privileges-con":[
							"指定Visa卡持卡人注册成为东航会员（包括手机会员及万里行会员）并登录后参与，每个账号仅限领取一次1,000元红包，东航官网定国际机票享受高达10%直减"
						]	
					},
					{
						"offer-privilege_name":"细则条款",
						"offer-privileges-con":[
							"适用范围：由东航、上航实际承运的国际及地区航线单程、往返程航班• 红包说明：价值1,000元的红包共含3张现金券：100元券一张（票价满1,000元可用），300元券一张（票价满3,000元可用）, 600元券一张（票价满6,000元可用）",
							"领取规则：仅限“东方万里行”会员领取，每个账户每月限领一次，红包有效期一个月，每日赠送数量有限，先到先得领完即止",
							"使用规则：领取的红包券仅限东航会员通过东航官网，为其本人购买指定国际客票时使用，支付时持卡人需用大陆发行的Visa指定卡并通过快钱支付通道完成付款",
							"详细条款与细则请参见www.visa.com.cn/premium或以东航官方公布信息为准",
							"优惠兑现和履行由优惠提供商全权负责",
							"Visa有权在任何时间、在未经事先通知的情况下修改或取消任何一项或所有优惠"
						]	
					},
					{
						"offer-privilege_name":"预定及使用方法",
						"offer-privileges-con":[
							"领取现金红包礼：注册成为“东方万里行“会员，于活动期间通过东航官网、东方航空APP领取价值1000元的现金红包礼",
							"使用红包券：仅限东航会员通过东航官网，为其本人购买指定国际客票，并使用中国大陆发行指定Visa卡并通过快钱支付通道完成付款 "
						]	
					},
					{
						"offer-privilege_name":"权益有效期",
						"offer-privileges-con":[
							"2017年1月1日 至 2017年12月31日"
						]	
					},
				]
			}
		]
	},
	{
		"offer_type":"酒店",
		"offer_code":"1001",
		"offer-airlines":[
			{
				"offer-vendor-name":"中国东方航空",
				"offer-vendor-intro":"东航航线覆盖全球179个国家、1057个目的地。是天合联盟成员。",
				"offer-rules":[
					{
						"offer-rule-title":"适用卡别:",
						"offer-rule-con":"金卡、白金卡、无限卡"
					},
					{
						"offer-rule-title":"发行地区:",
						"offer-rule-con":"中国大陆"
					},
					{
						"offer-rule-title":"兑现城市:",
						"offer-rule-con":"中国多个城市"
					}
				],
				"offer-privileges":[
					{
						"offer-privilege_name":"尊享礼遇",
						"offer-privileges-con":[
							"指定Visa卡持卡人注册成为东航会员（包括手机会员及万里行会员）并登录后参与，每个账号仅限领取一次1,000元红包，东航官网定国际机票享受高达10%直减"
						]	
					},
					{
						"offer-privilege_name":"细则条款",
						"offer-privileges-con":[
							"适用范围：由东航、上航实际承运的国际及地区航线单程、往返程航班• 红包说明：价值1,000元的红包共含3张现金券：100元券一张（票价满1,000元可用），300元券一张（票价满3,000元可用）, 600元券一张（票价满6,000元可用）",
							"领取规则：仅限“东方万里行”会员领取，每个账户每月限领一次，红包有效期一个月，每日赠送数量有限，先到先得领完即止",
							"使用规则：领取的红包券仅限东航会员通过东航官网，为其本人购买指定国际客票时使用，支付时持卡人需用大陆发行的Visa指定卡并通过快钱支付通道完成付款",
							"详细条款与细则请参见www.visa.com.cn/premium或以东航官方公布信息为准",
							"优惠兑现和履行由优惠提供商全权负责",
							"Visa有权在任何时间、在未经事先通知的情况下修改或取消任何一项或所有优惠"
						]	
					},
					{
						"offer-privilege_name":"预定及使用方法",
						"offer-privileges-con":[
							"领取现金红包礼：注册成为“东方万里行“会员，于活动期间通过东航官网、东方航空APP领取价值1000元的现金红包礼",
							"使用红包券：仅限东航会员通过东航官网，为其本人购买指定国际客票，并使用中国大陆发行指定Visa卡并通过快钱支付通道完成付款 "
						]	
					},
					{
						"offer-privilege_name":"权益有效期",
						"offer-privileges-con":[
							"2017年1月1日 至 2017年12月31日"
						]	
					},
				]
			}
		]
	}
]